# Generated by Django 5.0.7 on 2024-07-31 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='category',
            field=models.CharField(choices=[('uncategorized', 'Uncategorized'), ('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snacks', 'Snacks')], default='uncategorized', max_length=20),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='food_name',
            field=models.CharField(max_length=200),
        ),
    ]
