# Generated by Django 5.0.7 on 2024-08-03 23:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0002_alter_diaryentry_category_alter_diaryentry_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalorieGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.PositiveIntegerField()),
                ('date_set', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='food_name',
            field=models.CharField(max_length=100),
        ),
    ]
